CREATE TABLE exercise_log (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  exercise_id INTEGER REFERENCES exercises(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id)
    ON DELETE SET NULL,
  set_count INTEGER,
  rep_count INTEGER,
  weight_count INTEGER,
  date_logged TIMESTAMPTZ DEFAULT now() NOT NULL
);